---
language: ruby
rvm:
- 1.9.3
- 2.0.0
env:
- REDMINE_VERSION=2.2.4
- REDMINE_VERSION=2.3.1
matrix:
  exclude:
  - rvm: 2.0.0
    env: REDMINE_VERSION=2.2.4
install: rake redmine:setup
script: rake spec
