sudo: false
language: ruby
cache:
  directories:
  - vendor/bundle
  - node_modules
rvm:
- '2.2'
- '2.1'
- 2.0.0
- 1.9.3
env:
- REDMINE_VERSION=3.0.2
- REDMINE_VERSION=master
matrix:
  allow_failures:
  - env: REDMINE_VERSION=master
  exclude:
  - env: REDMINE_VERSION=2.6.3
    rvm: '2.2'
branches:
  except:
  - debian
install:
- export BUNDLE_GEMFILE=""
- export BUNDLE_PATH="$(pwd)/vendor/bundle"
- bundle install --jobs=3 --retry=3 --path $BUNDLE_PATH
- npm install
- ./redmine update
script:
- make all
- bundle exec rake spec
