---
sudo: false
language: ruby
cache:
- directories:
  - vendor
  - node_modules
env:
- REDMINE_VERSION=2.6.0
- REDMINE_VERSION=2.5.3
- REDMINE_VERSION=2.4.7
- REDMINE_VERSION=master
rvm:
- 2.1
- 2.0.0
- 1.9.3
matrix:
  allow_failures:
  - env: REDMINE_VERSION=master
install:
- export BUNDLE_GEMFILE=""
- export BUNDLE_PATH="$(pwd)/vendor/bundle"
- npm update
- ./redmine update
- bundle install --jobs=3 --retry=3 --path $BUNDLE_PATH
script:
- make all
- bundle exec rake spec
- ./redmine cleanup
