---
language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
env:
- REDMINE_VERSION=2.1.6
- REDMINE_VERSION=2.2.4
- REDMINE_VERSION=2.3.4
- REDMINE_VERSION=2.4.2
- REDMINE_VERSION=master
matrix:
  allow_failures:
  - env: REDMINE_VERSION=master
  exclude:
  - rvm: 2.0.0
    env: REDMINE_VERSION=2.2.4
  - rvm: 2.0.0
    env: REDMINE_VERSION=2.1.6
  - rvm: 2.1.0
    env: REDMINE_VERSION=2.2.4
  - rvm: 2.1.0
    env: REDMINE_VERSION=2.1.6
before_script: bundle exec rake install
script: bundle exec rake spec
