---
sudo: false
language: ruby
cache:
- bundler
- npm
- bower
- directories:
  - tmp/redmine/2.6.0
  - tmp/redmine/2.5.3
  - tmp/redmine/2.4.7
rvm:
- 2.1
- 2.0.0
- 1.9.3
env:
- REDMINE_VERSION=2.6.0
- REDMINE_VERSION=2.5.3
- REDMINE_VERSION=2.4.7
- REDMINE_VERSION=master
matrix:
  allow_failures:
  - env: REDMINE_VERSION=master
before_script:
- npm install -g bower
- make install
- bundle exec rake install
script:
- make min
- bundle exec rake spec
