sudo: false
language: ruby
cache:
  directories:
  - vendor/bundle
  - node_modules
rvm:
- '2.2'
- '2.1'
- 2.0.0
env:
- REDMINE_VERSION=3.0.3
- REDMINE_VERSION=master
matrix:
  allow_failures:
  - env: REDMINE_VERSION=master
branches:
  except:
  - debian
install:
- npm config set spin=false
- export BUNDLE_GEMFILE=""
- export BUNDLE_PATH="$(pwd)/vendor/bundle"
- bundle install --jobs=3 --retry=3 --without development
- npm update
- BUNDLE_OPTS="--without development" ./redmine update
script:
- make production
- bundle exec rake spec
