---
sudo: false
language: ruby
cache:
- directories:
  - vendor/bundle
  - tmp/redmine
  - node_modules
rvm:
- 2.1
- 2.0.0
- 1.9.3
env:
- REDMINE_VERSION=2.6.0
- REDMINE_VERSION=2.5.3
- REDMINE_VERSION=2.4.7
- REDMINE_VERSION=master
matrix:
  allow_failures:
  - env: REDMINE_VERSION=master
install:
- export BUNDLE_GEMFILE=""
- export BUNDLE_PATH="$(pwd)/vendor/bundle"
- "bundle install --jobs=3 --retry=3 --path ${BUNDLE_PATH}"
- npm update
- ./redmine update
script:
- make min
- bundle exec rake spec
after_script:
- ./redmine cleanup
